# Generated by Django 3.1.6 on 2021-03-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='nro_chasis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nro_motor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
