# Generated by Django 3.1.6 on 2021-02-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.persona'),
        ),
    ]
