# Generated by Django 3.1.7 on 2021-05-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20210503_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconductor',
            name='created_at',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='estaciones',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestaciones',
            name='created_at',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
