# Generated by Django 3.1.6 on 2021-02-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20210212_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fech_nac',
            field=models.DateField(default='2020-06-11'),
            preserve_default=False,
        ),
    ]
