# Generated by Django 3.1.6 on 2021-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20210315_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
