# Generated by Django 3.1.7 on 2021-05-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20210503_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='estaciones',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalconductor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalestaciones',
            name='created_at',
        ),
    ]
