# Generated by Django 3.1.7 on 2021-06-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20210530_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estaciones',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='historicalestaciones',
            name='ruta',
        ),
        migrations.AddField(
            model_name='historicalviaje',
            name='km_ruta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='km_ruta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estaciones',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.distrito'),
        ),
        migrations.AlterField(
            model_name='historicalestaciones',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Web.distrito'),
        ),
    ]
