# Generated by Django 3.1.7 on 2021-05-04 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20210503_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tip_doc',
            field=models.CharField(choices=[('', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='tip_doc',
            field=models.IntegerField(choices=[('', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalconductor',
            name='tip_doc',
            field=models.IntegerField(choices=[('', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalpersona',
            name='tip_doc',
            field=models.IntegerField(choices=[('', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], default=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tip_doc',
            field=models.IntegerField(choices=[('', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], default=1),
        ),
        migrations.CreateModel(
            name='HistoricalEmpresa',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid_empresa', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('banco', models.CharField(max_length=100, null=True)),
                ('banco_abr', models.CharField(max_length=100, null=True)),
                ('cta_corriente', models.CharField(max_length=100, null=True)),
                ('cci', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical empresa',
                'db_table': 'Web_Historial_Empresa',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
