# Generated by Django 3.1.6 on 2021-03-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20210316_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='codigoImagen',
        ),
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='codigoPosicion',
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo2/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo2/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='PosicionesLlantas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(blank=True, default=True)),
                ('posx', models.IntegerField(blank=True, default=True)),
                ('posy', models.IntegerField(blank=True, default=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.tipovehiculo')),
            ],
        ),
    ]
