# Generated by Django 3.1.6 on 2021-02-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20210217_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubierta',
            name='fech',
            field=models.DateField(blank=True, null=True),
        ),
    ]
