# Generated by Django 3.1.7 on 2021-06-01 13:49

from django.db import migrations

def cargar_datos_desde_sql():
    from django.conf import settings
    base_dir=settings.BASE_DIR
    import os
    sql_script=open(os.path.join(base_dir,'Web/sql/migracion.sql'),"r").read()
    return sql_script
class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20210601_1314'),
    ]

    operations = [
        migrations.RunSQL(cargar_datos_desde_sql())
    ]
