# Generated by Django 3.1.6 on 2021-03-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20210316_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicionesllantas',
            name='posx',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='posicionesllantas',
            name='posy',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/vehiculo2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/vehiculo2/%Y/%m/%d'),
        ),
    ]
