# Generated by Django 3.1.7 on 2021-05-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20210504_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='uuid_empresa',
        ),
        migrations.RemoveField(
            model_name='historicalempresa',
            name='uuid_empresa',
        ),
    ]
