# Generated by Django 3.1.7 on 2021-06-12 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_auto_20210601_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrendimiento',
            old_name='rend_cargado',
            new_name='gal_abast',
        ),
        migrations.RenameField(
            model_name='rendimiento',
            old_name='rend_cargado',
            new_name='gal_abast',
        ),
        migrations.RemoveField(
            model_name='historicalrendimiento',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='historicalrendimiento',
            name='rend_prom',
        ),
        migrations.RemoveField(
            model_name='historicalrendimiento',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='historicalruta',
            name='km',
        ),
        migrations.RemoveField(
            model_name='historicalruta',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='historicalruta',
            name='rend',
        ),
        migrations.RemoveField(
            model_name='historicalruta',
            name='volumen',
        ),
        migrations.RemoveField(
            model_name='historicalviaje',
            name='km_ruta',
        ),
        migrations.RemoveField(
            model_name='historicalviaje',
            name='rend_cargado',
        ),
        migrations.RemoveField(
            model_name='historicalviaje',
            name='rend_prom',
        ),
        migrations.RemoveField(
            model_name='historicalviaje',
            name='rend_vacio',
        ),
        migrations.RemoveField(
            model_name='rendimiento',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='rendimiento',
            name='rend_prom',
        ),
        migrations.RemoveField(
            model_name='rendimiento',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='km',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='rend',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='volumen',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='km_ruta',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='rend_cargado',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='rend_prom',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='rend_vacio',
        ),
        migrations.AddField(
            model_name='detalleabastecimiento',
            name='afectacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detalleabastecimiento',
            name='gal_obj',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleabastecimiento',
            name='recorrido_obj',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleabastecimiento',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalrendimiento',
            name='modelo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Web.modelovehiculo'),
        ),
        migrations.AddField(
            model_name='historicalrendimiento',
            name='tramo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Web.tramo'),
        ),
        migrations.AddField(
            model_name='historicaltramo',
            name='formato',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaltramo',
            name='ids',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Web.modelovehiculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='tramo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Web.tramo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tramo',
            name='formato',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tramo',
            name='ids',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalleabastecimiento',
            name='volumen',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalAfectacionConsumo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('per_carga', models.IntegerField()),
                ('afectacion', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical afectacion consumo',
                'db_table': 'Web_Historial_AfectacionConsumo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AfectacionConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_carga', models.IntegerField()),
                ('afectacion', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
