# Generated by Django 3.1.7 on 2021-05-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_auto_20210504_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleabastecimiento',
            name='fech_hora',
        ),
        migrations.AddField(
            model_name='detalleabastecimiento',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
