# Generated by Django 3.1.6 on 2021-02-18 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_auto_20210217_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_doc', models.CharField(choices=[('', ' --- '), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], max_length=50)),
                ('nr_doc', models.CharField(max_length=20, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('tel', models.CharField(max_length=8, verbose_name='telefono')),
                ('cel', models.CharField(max_length=9, verbose_name='Celular')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('referecias', models.CharField(max_length=150, verbose_name='Referencias')),
                ('departa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.departamento', verbose_name='departamento')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.distrito', verbose_name='Provincia')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.provincia', verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, verbose_name='ruc')),
                ('rsocial', models.CharField(max_length=100, verbose_name='Razon Social')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.contacto', verbose_name='Contacto')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_modified', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.tiposervicio', verbose_name='Servicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='km',
        ),
        migrations.AlterField(
            model_name='llanta',
            name='acciones',
            field=models.CharField(choices=[(1, 'SEGUIMIENTO'), (2, 'CONFORME'), (3, 'NIVELAR PRESIONES'), (4, 'AJUSTE ESPARRAGOS'), (5, 'SALIDA ROTACION'), (6, 'SALIDA ALMACEN'), (7, 'SALIDA REENCAUCHE'), (8, 'SALIDA REPARACION'), (9, 'SALIDA A SCRAP')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='obs',
            field=models.CharField(choices=[(1, 'DESG. IRREGULAR'), (2, 'EDITAMENTO'), (3, 'CORTE EN BANDA'), (4, 'CORTE EN FLANCO'), (5, 'SEPARACION EN FLANCO'), (6, 'PROX. REENCAUCHE'), (7, 'PARA REENCAUCHE'), (8, 'CONFORME\t'), (9, 'INOPERATIVA'), (10, 'ROTACIÓN')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Renovadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('diseño', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renovadora_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renovadora_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedordireccion_created', to=settings.AUTH_USER_MODEL)),
                ('direc', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.direccion')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedordireccion_modified', to=settings.AUTH_USER_MODEL)),
                ('prov', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CubiertaLlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_ren', models.CharField(blank=True, max_length=2, null=True)),
                ('cubierta', models.CharField(choices=[('1', 'Nuevo'), ('2', 'Reencauchado')], default='1', max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fech_ren', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('ancho_banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.anchobandarenova')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cubiertallanta_created', to=settings.AUTH_USER_MODEL)),
                ('modelo_renova', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.modelorenova')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cubiertallanta_modified', to=settings.AUTH_USER_MODEL)),
                ('renovadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.renovadora', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.cliente', verbose_name='cliente')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientedireccion_created', to=settings.AUTH_USER_MODEL)),
                ('direc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.direccion', verbose_name='direccion')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientedireccion_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.contacto', verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
