# Generated by Django 3.1.6 on 2021-02-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_auto_20210218_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cubiertallanta',
            old_name='cubierta',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='llanta',
            name='cubierta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.cubiertallanta', verbose_name='Cubierta'),
        ),
    ]
