# Generated by Django 3.1.7 on 2021-07-06 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_auto_20210612_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='afectacionconsumo',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='afectacionconsumo',
            name='placa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Web.vehiculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estaciones',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacionproducto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacionproducto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalafectacionconsumo',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalafectacionconsumo',
            name='placa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Web.vehiculo'),
        ),
        migrations.AddField(
            model_name='historicalconductor',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalestaciones',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalestacionproducto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalestacionproducto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrendimiento',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalruta',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalunidadmedida',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruta',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='afectacionconsumo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tip_doc',
            field=models.CharField(choices=[('0', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='tip_doc',
            field=models.IntegerField(choices=[('0', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalafectacionconsumo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalconductor',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalconductor',
            name='tip_doc',
            field=models.IntegerField(choices=[('0', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalpersona',
            name='tip_doc',
            field=models.IntegerField(choices=[('0', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalrendimiento',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalrendimiento',
            name='fech_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalunidadmedida',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tip_doc',
            field=models.IntegerField(choices=[('0', 'Seleccione...'), (1, 'DNI'), (2, 'Carnet Extranjería'), (3, 'Pasaporte'), (4, 'RUC')], default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='fech_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
