# Generated by Django 3.1.6 on 2021-03-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_auto_20210317_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicionesllantas',
            name='repuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='max_rep',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posicionesllantas',
            name='posicion',
            field=models.IntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='posicionesllantas',
            name='posx',
            field=models.IntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='posicionesllantas',
            name='posy',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
