# Generated by Django 3.1.6 on 2021-02-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_auto_20210218_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubiertallanta',
            name='ancho_banda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.anchobandarenova'),
        ),
        migrations.AlterField(
            model_name='cubiertallanta',
            name='fech_ren',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cubiertallanta',
            name='modelo_renova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.modelorenova'),
        ),
        migrations.AlterField(
            model_name='cubiertallanta',
            name='renovadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.renovadora', verbose_name=''),
        ),
    ]
