# Generated by Django 3.1.7 on 2021-05-12 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_auto_20210512_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducto',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='historicalproducto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='historicalproducto',
            name='pre_fech_fin',
        ),
        migrations.RemoveField(
            model_name='historicalproducto',
            name='pre_fech_ini',
        ),
        migrations.RemoveField(
            model_name='historicalproducto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='historicalrendimiento',
            name='galones',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pre_fech_fin',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pre_fech_ini',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='rendimiento',
            name='galones',
        ),
        migrations.CreateModel(
            name='HistoricalEstacionProducto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(blank=True, editable=False)),
                ('pre_fech_fin', models.DateField(null=True)),
                ('pre_fech_ini', models.DateField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Web.estaciones')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Web.producto')),
            ],
            options={
                'verbose_name': 'historical estacion producto',
                'db_table': 'Web_Historial_EstacionProductos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EstacionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pre_fech_fin', models.DateField(null=True)),
                ('pre_fech_ini', models.DateField(null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.estaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.producto')),
            ],
        ),
    ]
