# Generated by Django 3.1.6 on 2021-02-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_auto_20210219_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubiertallanta',
            name='ancho_banda',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.anchobandarenova'),
        ),
        migrations.AlterField(
            model_name='cubiertallanta',
            name='modelo_renova',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.modelorenova'),
        ),
        migrations.AlterField(
            model_name='cubiertallanta',
            name='renovadora',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.renovadora', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='acciones',
            field=models.CharField(choices=[('1', 'SEGUIMIENTO'), ('2', 'CONFORME'), ('3', 'NIVELAR PRESIONES'), ('4', 'AJUSTE ESPARRAGOS'), ('5', 'SALIDA ROTACION'), ('6', 'SALIDA ALMACEN'), ('7', 'SALIDA REENCAUCHE'), ('8', 'SALIDA REPARACION'), ('9', 'SALIDA A SCRAP')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='obs',
            field=models.CharField(choices=[('1', 'DESG. IRREGULAR'), ('2', 'EDITAMENTO'), ('3', 'CORTE EN BANDA'), ('4', 'CORTE EN FLANCO'), ('5', 'SEPARACION EN FLANCO'), ('6', 'PROX. REENCAUCHE'), ('7', 'PARA REENCAUCHE'), ('8', 'CONFORME\t'), ('9', 'INOPERATIVA'), ('10', 'ROTACIÓN')], max_length=20, null=True),
        ),
    ]
