# Generated by Django 3.1.7 on 2021-05-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_auto_20210512_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalflota',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalflota',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='historicalflota',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalflota',
            name='placa',
        ),
        migrations.AddField(
            model_name='historicalvehiculo',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Web.empresa', verbose_name=''),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.empresa', verbose_name=''),
        ),
        migrations.DeleteModel(
            name='Flota',
        ),
        migrations.DeleteModel(
            name='HistoricalFlota',
        ),
    ]
