# Generated by Django 3.1.6 on 2021-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_auto_20210317_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovehiculo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo2/%Y/%m/%d'),
        ),
    ]
