# Generated by Django 3.1.6 on 2021-02-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_auto_20210219_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubiertallanta',
            name='renovadora',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.renovadora'),
        ),
    ]
