# Generated by Django 3.1.6 on 2021-02-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_auto_20210219_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubiertallanta',
            name='nro_ren',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
