# Generated by Django 3.1.6 on 2021-03-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_auto_20210318_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='nro_llantas_repuesto',
        ),
    ]
