# Generated by Django 3.1.6 on 2021-02-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0012_auto_20210219_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='llanta',
            name='marca_llanta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.marcallanta'),
        ),
    ]
