# Generated by Django 3.1.6 on 2021-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0012_remove_vehiculo_nro_llantas_repuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialllantas',
            name='estado',
            field=models.CharField(choices=[('1', '\tNUEVO'), ('2', 'REENCAUCHE')], max_length=2),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='estado',
            field=models.CharField(choices=[('1', '\tNUEVO'), ('2', 'REENCAUCHE')], max_length=9),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='max_rep',
            field=models.IntegerField(default=0),
        ),
    ]
