# Generated by Django 3.1.6 on 2021-04-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0013_auto_20210401_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='cubierta',
        ),
        migrations.AddField(
            model_name='cubiertallanta',
            name='llanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.llanta', verbose_name='Llanta'),
        ),
    ]
