# Generated by Django 3.1.6 on 2021-02-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0013_auto_20210220_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='posicion',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
