# Generated by Django 3.1.6 on 2021-04-02 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0014_auto_20210401_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubiertallanta',
            name='a_final',
        ),
        migrations.RemoveField(
            model_name='cubiertallanta',
            name='a_inicial',
        ),
        migrations.RemoveField(
            model_name='cubiertallanta',
            name='a_promedio',
        ),
        migrations.RemoveField(
            model_name='cubiertallanta',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='cubiertallanta',
            name='fech_ren',
        ),
        migrations.AddField(
            model_name='llanta',
            name='a_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llanta',
            name='a_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llanta',
            name='a_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llanta',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llanta',
            name='fech_ren',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
