# Generated by Django 3.1.6 on 2021-02-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0014_auto_20210220_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidallanta',
            name='capas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
