# Generated by Django 3.1.6 on 2021-04-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0015_auto_20210401_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubiertallanta',
            name='alt_prom',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cubiertallanta',
            name='fech_ren',
            field=models.DateField(null=True),
        ),
    ]
