# Generated by Django 3.1.6 on 2021-02-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0016_auto_20210221_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medidallanta',
            name='capas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
