# Generated by Django 3.1.6 on 2021-04-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0016_auto_20210402_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubiertallanta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cubiertallanta',
            name='primer_reen',
            field=models.BooleanField(default=False),
        ),
    ]
