# Generated by Django 3.1.6 on 2021-04-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0017_auto_20210402_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubiertallanta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
