# Generated by Django 3.1.6 on 2021-02-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0018_auto_20210221_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorenova',
            name='profundidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
