# Generated by Django 3.1.6 on 2021-02-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0019_modelorenova_profundidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='serie',
        ),
    ]
