# Generated by Django 3.1.6 on 2021-02-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0021_llanta_repuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='acciones',
        ),
    ]
