# Generated by Django 3.1.6 on 2021-02-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0022_remove_llanta_acciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='obs',
        ),
    ]
