# Generated by Django 3.1.6 on 2021-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0024_auto_20210223_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
