# Generated by Django 3.1.6 on 2021-02-25 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0025_vehiculo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubiertallanta',
            name='categoria',
            field=models.CharField(choices=[('1', 'Nuevo'), ('2', 'Reencauchado')], default='1', max_length=10),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.CharField(max_length=20)),
                ('profundidad', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=10)),
                ('posicion', models.CharField(max_length=2)),
                ('llanta', models.CharField(max_length=20)),
                ('condicion', models.CharField(choices=[('1', 'Nuevo'), ('2', 'Reencauchado')], max_length=50, verbose_name='Condición')),
                ('obs', models.CharField(choices=[('1', 'DESG. IRREGULAR'), ('2', 'EDITAMENTO'), ('3', 'CORTE EN BANDA'), ('4', 'CORTE EN FLANCO'), ('5', 'SEPARACION EN FLANCO'), ('6', 'PROX. REENCAUCHE'), ('7', 'PARA REENCAUCHE'), ('8', 'CONFORME\t'), ('9', 'INOPERATIVA'), ('10', 'ROTACIÓN')], max_length=20)),
                ('ubicacion', models.CharField(choices=[('1', 'Almacen'), ('2', 'Reencauche'), ('3', 'Taller'), ('4', 'Scrap'), ('5', 'Otros')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
