# Generated by Django 3.1.6 on 2021-02-25 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0027_auto_20210225_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialllantas',
            name='llanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.llanta'),
        ),
    ]
