# Generated by Django 3.1.6 on 2021-02-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0028_auto_20210225_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialllantas',
            name='condicion',
        ),
    ]
