# Generated by Django 3.1.6 on 2021-02-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0029_remove_historialllantas_condicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialllantas',
            name='placa',
        ),
        migrations.AddField(
            model_name='historialllantas',
            name='acciones',
            field=models.CharField(blank=True, choices=[('1', 'SEGUIMIENTO'), ('2', 'CONFORME'), ('3', 'NIVELAR PRESIONES'), ('4', 'AJUSTE ESPARRAGOS'), ('5', 'SALIDA ROTACION'), ('6', 'SALIDA ALMACEN'), ('7', 'SALIDA REENCAUCHE'), ('8', 'SALIDA REPARACION'), ('9', 'SALIDA A SCRAP')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historialllantas',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='historialllantas',
            name='obs',
            field=models.CharField(choices=[('1', 'DESG. IRREGULAR'), ('2', 'EDITAMENTO'), ('3', 'CORTE EN BANDA'), ('4', 'CORTE EN FLANCO'), ('5', 'SEPARACION EN FLANCO'), ('6', 'PROX. REENCAUCHE'), ('7', 'PARA REENCAUCHE'), ('8', 'CONFORME\t'), ('9', 'INOPERATIVA'), ('10', 'ROTACIÓN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historialllantas',
            name='posicion',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='historialllantas',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.ubicacion'),
        ),
    ]
