# Generated by Django 3.1.6 on 2021-02-26 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0030_auto_20210225_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialllantas',
            name='acciones',
        ),
        migrations.AddField(
            model_name='historialllantas',
            name='eliminado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historialllantas',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.estadollanta'),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[(1, 'MONTADO'), (2, 'DESMONTADO')], max_length=50, null=True),
        ),
    ]
