# Generated by Django 3.1.6 on 2021-02-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0031_auto_20210226_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='ubicacion',
        ),
    ]
