# Generated by Django 3.1.6 on 2021-02-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0032_remove_llanta_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.ubicacion'),
        ),
    ]
