# Generated by Django 3.1.6 on 2021-02-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0033_llanta_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InpeccionLlantas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='operacion',
            field=models.CharField(blank=True, choices=[('1', 'COMBUSTIBLE'), ('2', 'MINERALES')], max_length=2, null=True),
        ),
    ]
