# Generated by Django 3.1.6 on 2021-02-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0034_auto_20210226_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialllantas',
            name='obs',
            field=models.CharField(blank=True, choices=[('1', 'DESG. IRREGULAR'), ('2', 'EDITAMENTO'), ('3', 'CORTE EN BANDA'), ('4', 'CORTE EN FLANCO'), ('5', 'SEPARACION EN FLANCO'), ('6', 'PROX. REENCAUCHE'), ('7', 'PARA REENCAUCHE'), ('8', 'CONFORME\t'), ('9', 'INOPERATIVA'), ('10', 'ROTACIÓN')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historialllantas',
            name='posicion',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
