# Generated by Django 3.1.6 on 2021-03-02 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0035_auto_20210228_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpeccionllantas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inpeccionllantas_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='eliminado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='fech_ins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='fech_km_ant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='km_act',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='km_re',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='km_ult',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inpeccionllantas_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='operacion',
            field=models.CharField(blank=True, choices=[('1', 'Combustible'), ('2', 'Minerales'), ('3', 'Mantenimiento'), ('4', 'Operaciones')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='supervisor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inpeccionllantas_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inpeccionllantas',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.vehiculo'),
        ),
        migrations.AlterField(
            model_name='historialllantas',
            name='km',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historialllantas',
            name='profundidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DetalleInspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(blank=True, max_length=5, null=True, verbose_name='Posicion')),
                ('cubierta', models.CharField(blank=True, choices=[('1', 'NVA'), ('2', 'R1'), ('3', 'R2'), ('4', 'R3'), ('5', 'R4')], max_length=10, null=True)),
                ('rem1', models.CharField(blank=True, max_length=5, null=True, verbose_name='Remanente 1')),
                ('rem2', models.CharField(blank=True, max_length=5, null=True, verbose_name='Remanente 2')),
                ('rem3', models.CharField(blank=True, max_length=5, null=True, verbose_name='Remanente 3')),
                ('rem_prom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Remanente promedio')),
                ('rem_max', models.CharField(blank=True, max_length=10, null=True, verbose_name='Remanente máximo')),
                ('rem_min', models.CharField(blank=True, max_length=10, null=True, verbose_name='Remanente mínimo')),
                ('pres_ini', models.CharField(blank=True, max_length=10, null=True, verbose_name='Presión inicial')),
                ('pres_fin', models.CharField(blank=True, max_length=10, null=True, verbose_name='Presión final')),
                ('obs', models.CharField(choices=[('1', 'DESG. IRREGULAR'), ('2', 'EDITAMENTO'), ('3', 'CORTE EN BANDA'), ('4', 'CORTE EN FLANCO'), ('5', 'SEPARACION EN FLANCO'), ('6', 'PROX. REENCAUCHE'), ('7', 'PARA REENCAUCHE'), ('8', 'CONFORME\t'), ('9', 'INOPERATIVA'), ('10', 'ROTACIÓN')], max_length=50, verbose_name='Observación')),
                ('accion', models.CharField(choices=[('1', 'SEGUIMIENTO'), ('2', 'CONFORME'), ('3', 'NIVELAR PRESIONES'), ('4', 'AJUSTE ESPARRAGOS'), ('5', 'SALIDA ROTACION'), ('6', 'SALIDA ALMACEN'), ('7', 'SALIDA REENCAUCHE'), ('8', 'SALIDA REPARACION'), ('9', 'SALIDA A SCRAP')], max_length=50, verbose_name='Acción')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalleinspeccion_created', to=settings.AUTH_USER_MODEL)),
                ('inspeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.inpeccionllantas', verbose_name='')),
                ('llanta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.llanta', verbose_name='Llanta')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalleinspeccion_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
