# Generated by Django 3.1.6 on 2021-03-02 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0036_auto_20210302_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpeccionllantas',
            name='tecnico',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inpeccionllantas_tecnico', to=settings.AUTH_USER_MODEL),
        ),
    ]
