# Generated by Django 3.1.6 on 2021-03-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0037_inpeccionllantas_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='obs',
            field=models.CharField(choices=[('1', 'DESG. IRREGULAR'), ('2', 'EDITAMENTO'), ('3', 'CORTE EN BANDA'), ('4', 'CORTE EN FLANCO'), ('5', 'SEPARACION EN FLANCO'), ('6', 'PROX. REENCAUCHE'), ('7', 'PARA REENCAUCHE'), ('8', 'CONFORME'), ('9', 'INOPERATIVA'), ('10', 'ROTACIÓN')], max_length=50, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem_max',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Presión inicial'),
        ),
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem_min',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Presión inicial'),
        ),
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem_prom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialllantas',
            name='obs',
            field=models.CharField(blank=True, choices=[('1', 'DESG. IRREGULAR'), ('2', 'EDITAMENTO'), ('3', 'CORTE EN BANDA'), ('4', 'CORTE EN FLANCO'), ('5', 'SEPARACION EN FLANCO'), ('6', 'PROX. REENCAUCHE'), ('7', 'PARA REENCAUCHE'), ('8', 'CONFORME'), ('9', 'INOPERATIVA'), ('10', 'ROTACIÓN')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inpeccionllantas',
            name='operacion',
            field=models.CharField(blank=True, choices=[('1', 'COMBUSTIBLE'), ('2', 'MINERALES'), ('3', 'MANTENIMIENTO'), ('4', 'OPERACIONES')], max_length=50, null=True),
        ),
    ]
