# Generated by Django 3.1.6 on 2021-03-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0039_remove_detalleinspeccion_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinspeccion',
            name='posicion',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Posicion'),
        ),
    ]
