# Generated by Django 3.1.6 on 2021-03-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0040_detalleinspeccion_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem_prom',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
