# Generated by Django 3.1.6 on 2021-03-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0041_auto_20210303_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detalleinspeccion',
            name='rem3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
