# Generated by Django 3.1.6 on 2021-03-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0042_auto_20210303_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinspeccion',
            name='repuesto',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
