# Generated by Django 3.1.6 on 2021-03-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0044_auto_20210303_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Correo electrónico'),
        ),
    ]
