# Generated by Django 3.1.6 on 2021-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0047_auto_20210305_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovehiculo',
            old_name='croquis',
            new_name='codigo',
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='imagen',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
