# Generated by Django 3.1.6 on 2021-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0048_auto_20210305_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovehiculo',
            old_name='imagen',
            new_name='codigoImagen',
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='codigoPosicion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
