# Generated by Django 3.1.6 on 2021-03-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0049_auto_20210305_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ubicacionv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.lugar', verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='cubiertallanta',
            name='ancho_banda',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.anchobandarenova'),
        ),
        migrations.AlterField(
            model_name='cubiertallanta',
            name='renovadora',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web.marcarenova'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='codigoImagen',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='codigoPosicion',
            field=models.CharField(max_length=20),
        ),
    ]
