# Generated by Django 3.1.6 on 2021-03-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0050_auto_20210307_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='marca_llanta',
        ),
        migrations.AddField(
            model_name='renovadora',
            name='diseño2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
