# Generated by Django 3.1.6 on 2021-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0051_auto_20210310_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='estado',
            field=models.CharField(choices=[('1', 'BAJA'), ('2', 'USADO'), ('3', 'REPARACIÓN'), ('4', 'ALMACÉN'), ('5', 'EVALUACIÓN'), ('6', 'TALLER MTNO'), ('7', 'REENCAUCHADO'), ('8', 'REPARADO'), ('9', 'NUEVO')], default='1', max_length=9),
            preserve_default=False,
        ),
    ]
