# Generated by Django 3.1.6 on 2021-03-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0052_auto_20210311_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llantas', to='Web.vehiculo'),
        ),
    ]
