# Generated by Django 3.1.6 on 2021-03-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0053_auto_20210311_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialllantas',
            name='estado',
            field=models.CharField(choices=[('1', 'BAJA'), ('2', 'USADO'), ('3', 'REPARACIÓN'), ('4', 'ALMACÉN'), ('5', 'EVALUACIÓN'), ('6', 'TALLER MTNO'), ('7', 'REENCAUCHADO'), ('8', 'REPARADO'), ('9', 'NUEVO')], default='1', max_length=2),
            preserve_default=False,
        ),
    ]
