# Generated by Django 3.1.6 on 2021-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0054_auto_20210311_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='operacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
