# Generated by Django 3.1.6 on 2021-03-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0055_auto_20210312_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
