#!/usr/bin/env python
# -*- coding: utf8 -*-


APP_GESTION = 1 # Modulo administrativo

CHOICES_APP = (
	(APP_GESTION, 'Gestión'),
)

ACCION_NUEVO = 1
ACCION_EDITAR = 2
ACCION_ELIMINAR = 3
ACCION_CERRAR_SESION = 4

ACCIONES = (ACCION_NUEVO, ACCION_EDITAR, ACCION_ELIMINAR, ACCION_CERRAR_SESION)

TIPO_DOC_SIN_DOC = ''
TIPO_DOC_DNI = 1
TIPO_DOC_CARNET_EXTRANJERIA = 2
TIPO_DOC_PASAPORTE = 3
TIPO_DOC_RUC=4
CHOICES_TIPO_DOC2 = (
	(TIPO_DOC_SIN_DOC, ' --- '),
	(TIPO_DOC_DNI, 'DNI'),
	(TIPO_DOC_CARNET_EXTRANJERIA, 'Carnet Extranjería'),
	(TIPO_DOC_PASAPORTE, 'Pasaporte'),
 	(TIPO_DOC_RUC, 'RUC'),

)

TIPO_SEXO_HOMBRE = 1
TIPO_SEXO_MUJER = 2
CHOICES_SEXO = (
	(TIPO_SEXO_HOMBRE, 'Hombre'),
	(TIPO_SEXO_MUJER, 'Mujer')
)


ESTADO_1 = 1
ESTADO_2 = 2
CHOICES_ESTADOS = (
	(ESTADO_1, 'Estado 1'),
	(ESTADO_2, 'Estado 2')
)