#!/usr/bin/env python
# -*- coding: utf8 -*-


APP_GESTION = 1 # Modulo administrativo

CHOICES_APP = (
	(APP_GESTION, 'Gestión'),
)

ACCION_NUEVO = 1
ACCION_EDITAR = 2
ACCION_ELIMINAR = 3
ACCION_CERRAR_SESION = 4

ACCIONES = (ACCION_NUEVO, ACCION_EDITAR, ACCION_ELIMINAR, ACCION_CERRAR_SESION)

TIPO_DOC_SIN_DOC = ''
TIPO_DOC_DNI = 1
TIPO_DOC_CARNET_EXTRANJERIA = 2
TIPO_DOC_PASAPORTE = 3
TIPO_DOC_RUC=4
CHOICES_TIPO_DOC2 = (
	(TIPO_DOC_SIN_DOC, 'Seleccione...'),
	(TIPO_DOC_DNI, 'DNI'),
	(TIPO_DOC_CARNET_EXTRANJERIA, 'Carnet Extranjería'),
	(TIPO_DOC_PASAPORTE, 'Pasaporte'),
 	(TIPO_DOC_RUC, 'RUC'),

)

TIPO_SEXO_HOMBRE = 1
TIPO_SEXO_MUJER = 2
CHOICES_SEXO = (
	(TIPO_SEXO_HOMBRE, 'Hombre'),
	(TIPO_SEXO_MUJER, 'Mujer')
)


ESTADO_1 = 1
ESTADO_2 = 2
CHOICES_ESTADOS = (
	(ESTADO_1, 'Estado 1'),
	(ESTADO_2, 'Estado 2')
)

CONDICION_1 = "1"
CONDICION_2 = "2"
CHOICES_CONDICION = (
	(CONDICION_1, 'Nuevo'),
	(CONDICION_2, 'Reencauchado')
)



OBSERVACION_1 = "1"
OBESERVACION_2 = "2"
OBESERVACION_3 = "3"
OBESERVACION_4 = "4"
OBESERVACION_5 = "5"
OBESERVACION_6 = "6"
OBESERVACION_7 = "7"
OBESERVACION_8 = "8"
OBESERVACION_9 = "9"
OBESERVACION_10 ="10"

CHOICES_OBSERVACION = (
	(OBSERVACION_1, 'DESG. IRREGULAR'),
	(OBESERVACION_2, 'EDITAMENTO'),
 	(OBESERVACION_3, 'CORTE EN BANDA'),
	(OBESERVACION_4, 'CORTE EN FLANCO'),
 	(OBESERVACION_5, 'SEPARACION EN FLANCO'),
	(OBESERVACION_6,'PROX. REENCAUCHE'),
 	(OBESERVACION_7, 'PARA REENCAUCHE'),
	(OBESERVACION_8, 'CONFORME'),
 	(OBESERVACION_9, 'INOPERATIVA'),
	(OBESERVACION_10, 'ROTACIÓN')
)


CHOICES_ACCION = (
	("1", 'SEGUIMIENTO'),
	("2", 'CONFORME'),
 	("3", 'NIVELAR PRESIONES'),
	("4", 'AJUSTE ESPARRAGOS'),
 	("5", 'SALIDA ROTACION'),
	("6",'SALIDA ALMACEN'),
 	("7", 'SALIDA REENCAUCHE'),
	("8", 'SALIDA REPARACION'),
 	("9", 'SALIDA A SCRAP'),
	
)

CHOICES_CUBIERTA = (
	(1, 'Nueva'),
	(2, 'Reencauchada'),
 
	
)
CHOICES_CUBIERTA_INSPECCION=(
      ("1", 'NVA'),
      ("2", 'R1'),
      ("3", 'R2'),
    ("4", 'R3'),
     ("5", 'R4'),
)
CHOICES_UBICACION_LLANTA = (
	("1", 'MONTADO'),
	("2", 'DESMONTADO'),
  
)
CHOICES_OPERACION = (
	("1", 'COMBUSTIBLE'),
	("2", 'MINERALES'),
  	("3", 'MANTENIMIENTO'),
  	("4", 'OPERACIONES'),

)
CHOICES_ESTADO_LLANTA = (
    ("1", '	NUEVO'),
	("2", 'REENCAUCHE'),
	# ("1", 'BAJA'),
	# ("2", 'USADO'),
  	# ("3", 'REPARACIÓN'),
  	# ("4", 'ALMACÉN'),
  	# ("5", 'EVALUACIÓN'),
  	# ("6", 'TALLER MTNO'),
  	# ("7", 'REENCAUCHADO'),
  	# ("8", 'REPARADO'),
  	# ("9", 'NUEVO'),

)